### ISSUE TITLE
작업할 때 브랜치 이용해서 하는 게 좋을 것 같아요!

### ISSUE THREAD

**Issue by skyla15** [CSID-DGU/2018-1-OSSP-Sophist-5#4]
실수로 테트리스 파일 커밋중에 window 자바파일을 삭제한 상태로 올려 다시 올렸습니다.
변경된 부분은 주석으로 표시해두었으니 확인해주세요.
Item / Sound 브랜치 따로 생성하여 작업할게요!

**Comment by taegun89** [comment]
네 알겠습니다.
