### ISSUE TITLE
아이템저장 및 타임어택 모드 

### ISSUE THREAD

**Issue by skyla15** [CSID-DGU/2018-1-OSSP-Sophist-5#6]
타임어택모드의 경우에도 아이템을 현재있는 것에서 추가하게 될 경우에 복잡하게 될 수도 있을것같아요.
그래서 점수모드로 하는 게 어떨까 합니다.

멀티윈도우랑 아이템 위치에 이미지 넣는 것까지만 진행한 뒤에 그 다음으로 진행하도록해요.

**Comment by TaeSuPark** [comment]
타임어택 모드에서는 아이템이 적용 안되지 않나요?

**Comment by TaeSuPark** [comment]
타임어택 모드는 라인이 깨질 때 시간이 더해지는 것만 추가적으로 구현하면 될거같습니다

**Comment by skyla15** [comment]
넹 그렇게해여
